version: '3.9'

networks:
  backend:
    driver: ${NETWORKS_DRIVER}

services:
### Workspace Utilities ##################################
  workspace:
    build:
      context: ./docker/workspace
      args:
        - PHP_VERSION=${PHP_VERSION}
        - COMPOSER_VERSION=${WORKSPACE_COMPOSER_VERSION}
        - PUID=${WORKSPACE_PUID}
        - PGID=${WORKSPACE_PGID}
        - TZ=${WORKSPACE_TIMEZONE}
        - http_proxy
        - no_proxy
    volumes:
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}${APP_CODE_CONTAINER_FLAG}
    tty: true
    networks:
      - backend

### PHP-FPM ##############################################
  php-fpm:
    build:
      context: docker/php-fpm
      args:
        - PHP_VERSION=${PHP_VERSION}
        - INSTALL_XDEBUG=${PHP_FPM_INSTALL_XDEBUG}
        - INSTALL_OPCACHE=${PHP_FPM_INSTALL_OPCACHE}
        - PUID=${PHP_FPM_PUID}
        - PGID=${PHP_FPM_PGID}
        - http_proxy
        - no_proxy
    volumes:
      - ./docker/php-fpm/php${PHP_VERSION}.ini:/usr/local/etc/php/php.ini
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}${APP_CODE_CONTAINER_FLAG}
    expose:
      - "9000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - backend

### NGINX Server #########################################
  nginx:
    build:
      context: docker/nginx
      args:
        - PHP_UPSTREAM_CONTAINER=${NGINX_PHP_UPSTREAM_CONTAINER}
        - PHP_UPSTREAM_PORT=${NGINX_PHP_UPSTREAM_PORT}
        - http_proxy
        - no_proxy
    volumes:
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}${APP_CODE_CONTAINER_FLAG}
      - ${NGINX_HOST_LOG_PATH}:/var/log/nginx
      - ${NGINX_SITES_PATH}:/etc/nginx/sites-available
    ports:
      - "${NGINX_HOST_HTTP_PORT}:80"
    depends_on:
      - php-fpm
    networks:
      - backend
