<?php

namespace App\Enum;

enum ErrorCodeEnum: string
{
    case UNRECOGNIZED_ERROR = 'UNRECOGNIZED_ERROR';
    case AUTH_INVALID_DATA_ERROR = 'AUTH_INVALID_DATA_ERROR';
    case AUTH_FAILED_ERROR = 'AUTH_FAILED_ERROR';
    case AUTH_EXPIRED_ERROR = 'AUTH_EXPIRED_ERROR';
    case REQUEST_QUOTA_ERROR = 'REQUEST_QUOTA_ERROR';
    case INTERNAL_ERROR = 'INTERNAL_ERROR';
    case CLIENT_ERROR = 'CLIENT_ERROR';
    case SOME_ITEMS_HAVE_ERRORS = 'SOME_ITEMS_HAVE_ERRORS';
    case ITEM_NOT_FOUND_ERROR = 'ITEM_NOT_FOUND_ERROR';
}
