<?php

namespace App\Enum;

enum ErrorCodeEnum: string
{
    case UNKNOWN_ERROR = 'UNKNOWN_ERROR';
    case AUTH_INVALID_DATA_ERROR = 'AUTH_INVALID_DATA_ERROR';
    case AUTH_FAILED_ERROR = 'AUTH_FAILED_ERROR';
    case AUTH_EXPIRED_ERROR = 'AUTH_EXPIRED_ERROR';
    case REQUEST_QUOTA_ERROR = 'REQUEST_QUOTA_ERROR';
    case ITEM_NOT_FOUND_ERROR = 'ITEM_NOT_FOUND_ERROR';
}
