services:
    App\Interfaces\Mapper\CacheItemMapperInterface:
        class: App\Tests\Functional\Integration\Mapper\CacheItemMapper

    App\Interfaces\Mapper\CacheMapperInterface:
        class: App\Tests\Functional\Integration\Mapper\CacheMapper

    App\Interfaces\Mapper\ContentItemMapperInterface:
        class: App\Tests\Functional\Integration\Mapper\ContentItemMapper

    App\Interfaces\Mapper\LocaleItemMapperInterface:
        class: App\Tests\Functional\Integration\Mapper\LocaleItemMapper

    App\Interfaces\Mapper\EnvItemMapperInterface:
        class: App\Tests\Functional\Integration\Mapper\EnvItemMapper
        arguments:
            - '@App\Interfaces\Mapper\LocaleItemMapperInterface'

    App\Interfaces\ApiClientInterface:
        class: App\Tests\Functional\Integration\ApiClient
