# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    App\ArgumentResolver\RequestDtoResolver:
        tags:
            - { name: controller.argument_value_resolver, priority: 50 }

    App\ArgumentResolver\TokenResolver:
        tags:
            - { name: controller.argument_value_resolver, priority: 50 }

    error_handler.error_renderer.serializer:
        alias: App\Renderer\ApiErrorRenderer

    App\TokenExtractor\TokenExtractorInterface:
        class: App\TokenExtractor\HeaderTokenExtractor

    App\Interfaces\Service\AuthenticationServiceInterface:
        class: App\Integration\Service\AuthenticationService

    App\Interfaces\Service\CacheServiceInterface:
        class: App\Integration\Service\CacheService

    App\Interfaces\Service\EnvironmentServiceInterface:
        class: App\Integration\Service\EnvironmentService

    App\Interfaces\Service\PublishServiceInterface:
        class: App\Integration\Service\PublishService

    App\Interfaces\Service\TranslationServiceInterface:
        class: App\Integration\Service\TranslationService

    App\Interfaces\Renderer\AuthRendererInterface:
        class: App\Integration\Renderer\AuthRenderer

    App\Interfaces\Renderer\RefreshRendererInterface:
        class: App\Integration\Renderer\RefreshRenderer

    App\Interfaces\Renderer\CacheRendererInterface:
        class: App\Integration\Renderer\CacheRenderer

    App\Interfaces\Renderer\CacheItemRendererInterface:
        class: App\Integration\Renderer\CacheItemRenderer

    App\Interfaces\Renderer\EnvironmentRendererInterface:
        class: App\Integration\Renderer\EnvironmentRenderer

    App\Interfaces\Renderer\PublishRendererInterface:
        class: App\Integration\Renderer\PublishRenderer

    App\Interfaces\Renderer\TranslationRendererInterface:
        class: App\Integration\Renderer\TranslationRenderer

    App\Interfaces\Mapper\CacheItemMapperInterface:
        class: App\Integration\Mapper\CacheItemMapper

    App\Interfaces\Mapper\CacheMapperInterface:
        class: App\Integration\Mapper\CacheMapper

    App\Interfaces\Mapper\ContentItemMapperInterface:
        class: App\Integration\Mapper\ContentItemMapper

    App\Interfaces\Mapper\EnvItemMapperInterface:
        class: App\Integration\Mapper\EnvItemMapper

    App\Interfaces\Mapper\LocaleItemMapperInterface:
        class: App\Integration\Mapper\LocaleItemMapper

    App\Interfaces\ApiClientInterface:
        class: App\Integration\ApiClient
