services:
    App\Interfaces\Service\AuthenticationServiceInterface:
        class: App\Tests\Functional\Integration\Service\AuthenticationService

    App\Interfaces\Service\CacheServiceInterface:
        class: App\Tests\Functional\Integration\Service\CacheService

    App\Interfaces\Service\EnvironmentServiceInterface:
        class: App\Tests\Functional\Integration\Service\EnvironmentService

    App\Interfaces\Service\TranslationServiceInterface:
        class: App\Tests\Functional\Integration\Service\TranslationService
