services:
    App\Interfaces\AuthenticationInterface:
        class: App\Tests\Integration\Service\AuthenticationTestService

    App\Interfaces\CacheInterface:
        class: App\Tests\Integration\Service\CacheTestService

    App\Interfaces\EnvironmentInterface:
        class: App\Tests\Integration\Service\EnvironmentTestService

    App\Interfaces\PublishInterface:
        class: App\Tests\Integration\Service\PublishTestService

    App\Interfaces\TranslationInterface:
        class: App\Tests\Integration\Service\TranslationTestService
