name: CI

on: [push]

jobs:
  phpunit:
    name: "PHPUnit"
    runs-on: "ubuntu-20.04"
    continue-on-error: false

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: "Install PHP with XDebug"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "8.1"
          coverage: "xdebug"
          tools: "composer:v2,flex"

      - name: "Cache dependencies installed with composer"
        uses: "actions/cache@v2"
        with:
          path: "~/.composer/cache"
          key: "php-8.1-composer-locked-${{ hashFiles('composer.lock') }}"
          restore-keys: "php-8.1-composer-locked-"

      - name: "Install dependencies with composer"
        env:
          SYMFONY_REQUIRE: "${{ matrix.symfony-require }}"
        run: |
          composer remove friendsofphp/php-cs-fixer --dev --no-update
          composer update --no-interaction --no-progress

      - name: "Run PHPUnit"
        run: |
          XDEBUG_MODE=coverage ./bin/phpunit --coverage-clover coverage.xml
          wget https://scrutinizer-ci.com/ocular.phar
          php ocular.phar code-coverage:upload --format=php-clover coverage.xml